/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import Objetos.CadConta;
import Objetos.Conta;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Ricardo
 */
public class Tela_Principal extends javax.swing.JFrame {
    String diretorio;
    /**
     * Creates new form Tela_Principal
     */
    public Tela_Principal(){        
        try{
            diretorio = System.getProperty("user.home");
            System.out.print(diretorio.replace("\\", "/"));
            diretorio +=  "\\Desktop\\Avaliacao_Banco.txt";
        }catch (Exception e){
            throw new Error(e);
        }
    
    
        initComponents();
        this.setLocationRelativeTo(null);
        this.Label_RegistrosCarregados.setVisible(false);
        this.cadContaObj = new CadConta();        
        try{
            cadContaObj.setArrayList(cadContaObj.LerArquivo(diretorio));
            this.Label_RegistrosCarregados.setText("Registros carregados com sucesso.");
            this.Label_RegistrosCarregados.setVisible(true);
            this.pausa();
        }catch(FileNotFoundException e){
            throw new Error(e);
        }
        
    }
    
    private void mensagemInicio(String mensagem){
        this.Label_RegistrosCarregados.setText(mensagem);
        this.Label_RegistrosCarregados.setVisible(true);
        this.pausa();
    }
    
    private void pausa(){
        Timer t = new Timer(3000, new ActionListener(){            
            public void actionPerformed(ActionEvent e) {
                Label_RegistrosCarregados.setVisible(false);
            }
        });
        
        t.setRepeats(false);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_RegistrosCarregados = new javax.swing.JLabel();
        MenuGeral = new javax.swing.JMenuBar();
        Menu_Contas = new javax.swing.JMenu();
        Item_CadastrarConta = new javax.swing.JMenuItem();
        Menu_Operacoes = new javax.swing.JMenu();
        Item_Deposito = new javax.swing.JMenuItem();
        Item_Saque = new javax.swing.JMenuItem();
        Item_Transferencia = new javax.swing.JMenuItem();
        Item_Consultar = new javax.swing.JMenuItem();
        Menu_Emprestimo = new javax.swing.JMenu();
        Item_RealizarEmprestimo = new javax.swing.JMenuItem();
        Menu_Salvar = new javax.swing.JMenu();
        Item_Salvar = new javax.swing.JMenuItem();
        Menu_Sair = new javax.swing.JMenu();
        Item_SairPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu_Contas.setText("Contas");

        Item_CadastrarConta.setText("Cadastrar");
        Item_CadastrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_CadastrarContaActionPerformed(evt);
            }
        });
        Menu_Contas.add(Item_CadastrarConta);

        MenuGeral.add(Menu_Contas);

        Menu_Operacoes.setText("Operações");

        Item_Deposito.setText("Depósito");
        Item_Deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_DepositoActionPerformed(evt);
            }
        });
        Menu_Operacoes.add(Item_Deposito);

        Item_Saque.setText("Saque");
        Item_Saque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_SaqueActionPerformed(evt);
            }
        });
        Menu_Operacoes.add(Item_Saque);

        Item_Transferencia.setText("Transferência");
        Item_Transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_TransferenciaActionPerformed(evt);
            }
        });
        Menu_Operacoes.add(Item_Transferencia);

        Item_Consultar.setText("Consultar");
        Item_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_ConsultarActionPerformed(evt);
            }
        });
        Menu_Operacoes.add(Item_Consultar);

        MenuGeral.add(Menu_Operacoes);

        Menu_Emprestimo.setText("Empréstimos");

        Item_RealizarEmprestimo.setText("Realizar Empréstimo");
        Item_RealizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_RealizarEmprestimoActionPerformed(evt);
            }
        });
        Menu_Emprestimo.add(Item_RealizarEmprestimo);

        MenuGeral.add(Menu_Emprestimo);

        Menu_Salvar.setText("Salvar Registros");

        Item_Salvar.setText("Salvar");
        Item_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_SalvarActionPerformed(evt);
            }
        });
        Menu_Salvar.add(Item_Salvar);

        MenuGeral.add(Menu_Salvar);

        Menu_Sair.setText("Sair");

        Item_SairPrograma.setText("Encerrar Programa");
        Item_SairPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_SairProgramaActionPerformed(evt);
            }
        });
        Menu_Sair.add(Item_SairPrograma);

        MenuGeral.add(Menu_Sair);

        setJMenuBar(MenuGeral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 317, Short.MAX_VALUE)
                .addComponent(Label_RegistrosCarregados, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(Label_RegistrosCarregados, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_CadastrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_CadastrarContaActionPerformed
        new Tela_Cadastro(cadContaObj).setVisible(true);
    }//GEN-LAST:event_Item_CadastrarContaActionPerformed

    private void Item_SairProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_SairProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Item_SairProgramaActionPerformed

    private void Item_DepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_DepositoActionPerformed
        new Tela_Deposito(this.cadContaObj).setVisible(true);
    }//GEN-LAST:event_Item_DepositoActionPerformed

    private void Item_SaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_SaqueActionPerformed
        new Tela_Saque(this.cadContaObj).setVisible(true);
    }//GEN-LAST:event_Item_SaqueActionPerformed

    private void Item_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_ConsultarActionPerformed
        new Tela_Consultar(this.cadContaObj).setVisible(true);
    }//GEN-LAST:event_Item_ConsultarActionPerformed

    private void Item_TransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_TransferenciaActionPerformed
        new Tela_Transferencia(this.cadContaObj).setVisible(true);
    }//GEN-LAST:event_Item_TransferenciaActionPerformed

    private void Item_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_SalvarActionPerformed
        try {
            this.cadContaObj.Salvar(diretorio);
        } catch (IOException ex) {
            Logger.getLogger(Tela_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Item_SalvarActionPerformed

    private void Item_RealizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_RealizarEmprestimoActionPerformed
        new Tela_RealizarEmprestimo(this.cadContaObj).setVisible(true);
    }//GEN-LAST:event_Item_RealizarEmprestimoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }
    
    private CadConta cadContaObj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Item_CadastrarConta;
    private javax.swing.JMenuItem Item_Consultar;
    private javax.swing.JMenuItem Item_Deposito;
    private javax.swing.JMenuItem Item_RealizarEmprestimo;
    private javax.swing.JMenuItem Item_SairPrograma;
    private javax.swing.JMenuItem Item_Salvar;
    private javax.swing.JMenuItem Item_Saque;
    private javax.swing.JMenuItem Item_Transferencia;
    private javax.swing.JLabel Label_RegistrosCarregados;
    private javax.swing.JMenuBar MenuGeral;
    private javax.swing.JMenu Menu_Contas;
    private javax.swing.JMenu Menu_Emprestimo;
    private javax.swing.JMenu Menu_Operacoes;
    private javax.swing.JMenu Menu_Sair;
    private javax.swing.JMenu Menu_Salvar;
    // End of variables declaration//GEN-END:variables
}