/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Objetos.CadConta;
import Objetos.Conta;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Ricardo
 */
public class Tela_Transferencia extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Transferencia
     */
    public Tela_Transferencia(CadConta cadContaObj) {
        initComponents();
        this.cadContaObj = cadContaObj;
        this.setLocationRelativeTo(null);
        this.Label_ConfirmacaoTransferencia.setVisible(false);
        this.Label_NumContaDestinoErro.setVisible(false);
        this.Label_NumContaOrigemErro.setVisible(false);
        this.Label_ValorTransferenciaErro.setVisible(false);
        this.Label_SaldoFinalContaOrigem.setVisible(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titulo = new javax.swing.JLabel();
        Label_NumContaOrigem = new javax.swing.JLabel();
        Label_NumContaOrigemErro = new javax.swing.JLabel();
        Input_NumContaOrigem = new javax.swing.JTextField();
        Label_NumContaDestino = new javax.swing.JLabel();
        Label_NumContaDestinoErro = new javax.swing.JLabel();
        Input_NumContaDestino = new javax.swing.JTextField();
        Label_ValorTransferencia = new javax.swing.JLabel();
        Input_ValorTransferencia = new javax.swing.JTextField();
        Label_ConfirmacaoTransferencia = new javax.swing.JLabel();
        Label_SaldoFinalContaOrigem = new javax.swing.JLabel();
        Label_SaldoFinalContaDestino = new javax.swing.JLabel();
        Button_Transferir = new javax.swing.JButton();
        Button_RetornarMenuPrincipal = new javax.swing.JButton();
        Label_ValorTransferenciaErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Titulo.setBackground(new java.awt.Color(168, 168, 168));
        Label_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Titulo.setText("Transferência");
        Label_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumContaOrigem.setBackground(new java.awt.Color(168, 168, 168));
        Label_NumContaOrigem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_NumContaOrigem.setText("Número da conta de origem");
        Label_NumContaOrigem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumContaOrigemErro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_NumContaOrigemErro.setForeground(java.awt.Color.red);

        Label_NumContaDestino.setBackground(new java.awt.Color(168, 168, 168));
        Label_NumContaDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_NumContaDestino.setText("Número da conta de destino");
        Label_NumContaDestino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumContaDestinoErro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_NumContaDestinoErro.setForeground(java.awt.Color.red);

        Label_ValorTransferencia.setBackground(new java.awt.Color(168, 168, 168));
        Label_ValorTransferencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_ValorTransferencia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_ValorTransferencia.setText("Valor da Transferência");
        Label_ValorTransferencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_ConfirmacaoTransferencia.setForeground(java.awt.Color.red);

        Button_Transferir.setText("Transferir");
        Button_Transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TransferirActionPerformed(evt);
            }
        });

        Button_RetornarMenuPrincipal.setText("Retornar ao menu principal");
        Button_RetornarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetornarMenuPrincipalActionPerformed(evt);
            }
        });

        Label_ValorTransferenciaErro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ValorTransferenciaErro.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_SaldoFinalContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_SaldoFinalContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_NumContaOrigem)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Label_NumContaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Label_ValorTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Input_NumContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Input_ValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Input_NumContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_Titulo))))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_NumContaOrigemErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NumContaDestinoErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ValorTransferenciaErro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Button_Transferir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(Label_ConfirmacaoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_RetornarMenuPrincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_NumContaOrigem)
                    .addComponent(Input_NumContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_NumContaOrigemErro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_NumContaDestino)
                        .addComponent(Input_NumContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_NumContaDestinoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_ValorTransferencia)
                        .addComponent(Input_ValorTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_ValorTransferenciaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Transferir)
                    .addComponent(Label_ConfirmacaoTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Label_SaldoFinalContaOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_SaldoFinalContaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(Button_RetornarMenuPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_TransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TransferirActionPerformed
        this.Label_NumContaOrigemErro.setText("");
        this.Label_NumContaOrigemErro.setVisible(false);
        this.Label_NumContaDestinoErro.setText("");
        this.Label_NumContaDestinoErro.setVisible(false);
        this.Label_ValorTransferenciaErro.setText("");
        this.Label_ValorTransferenciaErro.setVisible(false);
        this.Label_ConfirmacaoTransferencia.setText("");
        this.Label_ConfirmacaoTransferencia.setForeground(Color.red);
        this.Label_ConfirmacaoTransferencia.setVisible(false);
        this.Label_SaldoFinalContaOrigem.setText("");
        this.Label_SaldoFinalContaOrigem.setVisible(false);
        this.Label_SaldoFinalContaDestino.setText("");
        this.Label_SaldoFinalContaDestino.setVisible(false);
        
        int numContaOrigem;
        int numContaDestino;
        double valorTransferencia;
        
        try{
            if (this.Input_NumContaOrigem.getText().isEmpty()){
                this.Label_NumContaOrigemErro.setText("Insira o número da conta de origem!");
                this.Label_NumContaOrigemErro.setVisible(true);
            }
            if (this.Input_NumContaDestino.getText().isEmpty()){
                this.Label_NumContaDestinoErro.setText("Insira o número da conta de destino!");
                this.Label_NumContaDestinoErro.setVisible(true);
            }
            if (this.Input_ValorTransferencia.getText().isEmpty()){
                this.Label_ValorTransferenciaErro.setText("Insira o valor da transferência!");
                this.Label_ValorTransferenciaErro.setVisible(true);
            }
            if ((!this.Input_NumContaOrigem.getText().isEmpty()) && (!this.Input_NumContaDestino.getText().isEmpty()) && (!this.Input_ValorTransferencia.getText().isEmpty())){
                numContaOrigem = Integer.parseInt(this.Input_NumContaOrigem.getText());
                numContaDestino = Integer.parseInt(this.Input_NumContaDestino.getText());
                valorTransferencia = Double.parseDouble(this.Input_ValorTransferencia.getText());
                ArrayList<Conta> listaLocal = cadContaObj.getArrayList();

                boolean contaOrigemCerta = false;
                boolean contaDestinoCerta = false;
                int posContaOrigem = -1;
                int posContaDestino = -1;
                for (int i=0; i<listaLocal.size(); i++){
                    if (listaLocal.get(i).getNumeroConta() == numContaOrigem){
                        contaOrigemCerta = true;
                        posContaOrigem = i;
                        if (listaLocal.get(i).getNumeroConta() == numContaDestino){
                            this.Label_ConfirmacaoTransferencia.setText("Impossível transferir: as contas de origem e destino são iguais.");
                            this.Label_ConfirmacaoTransferencia.setVisible(true);
                            this.Input_NumContaOrigem.setText("");
                            this.Input_NumContaDestino.setText("");
                            break;
                        }
                    }
                    if (listaLocal.get(i).getNumeroConta() == numContaDestino) {
                        contaDestinoCerta = true;
                        posContaDestino = i;
                    }
                    if (i == listaLocal.size() - 1){
                        if (posContaOrigem == -1) {
                            this.Label_NumContaOrigemErro.setText("A conta de origem não existe!");
                            this.Label_NumContaOrigemErro.setVisible(true);
                        }
                        if (posContaDestino == -1){
                            this.Label_NumContaDestinoErro.setText("A conta de destino não existe!");
                            this.Label_NumContaDestinoErro.setVisible(true);
                        }
                    }
                }
                
                if ((contaOrigemCerta == true) && (contaDestinoCerta == true)){
                    cadContaObj.setArrayList(listaLocal);
                    this.Label_ConfirmacaoTransferencia.setText("");
                    this.Label_ConfirmacaoTransferencia.setVisible(false);
                    ArrayList<Conta> ListaTeste = cadContaObj.getArrayList();
                    if (listaLocal.get(posContaOrigem).Transferencia(valorTransferencia, listaLocal.get(posContaDestino)) == 1){
                        this.Label_ConfirmacaoTransferencia.setText("Transferência realizada com sucesso.");
                        this.Label_ConfirmacaoTransferencia.setForeground(Color.black);
                        this.Label_ConfirmacaoTransferencia.setVisible(true);
                        this.Label_SaldoFinalContaOrigem.setText("Saldo da conta de origem: R$" +ListaTeste.get(posContaOrigem).getSaldo());
                        this.Label_SaldoFinalContaOrigem.setVisible(true);
                        this.Label_SaldoFinalContaDestino.setText("Saldo da conta de destino: R$" +ListaTeste.get(posContaDestino).getSaldo());
                        this.Label_SaldoFinalContaDestino.setVisible(true);
                        this.Input_NumContaOrigem.setText("");
                        this.Input_NumContaDestino.setText("");
                        this.Input_ValorTransferencia.setText("");
                    }else if (listaLocal.get(posContaOrigem).Transferencia(valorTransferencia, listaLocal.get(posContaDestino)) == 2){
                        this.Label_ConfirmacaoTransferencia.setText("Ocorreu um erro na Transferencia()");
                        this.Label_ConfirmacaoTransferencia.setVisible(true);                        
                    }else if (listaLocal.get(posContaOrigem).Transferencia(valorTransferencia, listaLocal.get(posContaDestino)) == 0){
                        this.Label_ConfirmacaoTransferencia.setText("A conta de origem não possui saldo suficiente.");
                        this.Label_ConfirmacaoTransferencia.setVisible(true);
                        this.Label_SaldoFinalContaOrigem.setText("Saldo da conta de origem: R$" +listaLocal.get(posContaOrigem).getSaldo());
                        this.Label_SaldoFinalContaOrigem.setVisible(true);                        
                    }
                }
            }
        }catch(NumberFormatException e){
            this.Label_ConfirmacaoTransferencia.setText("Apenas números são válidos");
            this.Input_NumContaOrigem.setText("");
            this.Input_NumContaDestino.setText("");
            this.Input_ValorTransferencia.setText("");
            this.Label_ConfirmacaoTransferencia.setVisible(true);
            this.Button_RetornarMenuPrincipal.setVisible(true);
        }
    }//GEN-LAST:event_Button_TransferirActionPerformed

    private void Button_RetornarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetornarMenuPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Button_RetornarMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */    
    
    private CadConta cadContaObj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_RetornarMenuPrincipal;
    private javax.swing.JButton Button_Transferir;
    private javax.swing.JTextField Input_NumContaDestino;
    private javax.swing.JTextField Input_NumContaOrigem;
    private javax.swing.JTextField Input_ValorTransferencia;
    private javax.swing.JLabel Label_ConfirmacaoTransferencia;
    private javax.swing.JLabel Label_NumContaDestino;
    private javax.swing.JLabel Label_NumContaDestinoErro;
    private javax.swing.JLabel Label_NumContaOrigem;
    private javax.swing.JLabel Label_NumContaOrigemErro;
    private javax.swing.JLabel Label_SaldoFinalContaDestino;
    private javax.swing.JLabel Label_SaldoFinalContaOrigem;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_ValorTransferencia;
    private javax.swing.JLabel Label_ValorTransferenciaErro;
    // End of variables declaration//GEN-END:variables
}
