/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;
import Objetos.CadConta;
import Objetos.Conta;
import java.util.ArrayList;
/**
 *
 * @author Ricardo
 */
public class Tela_Deposito extends javax.swing.JFrame {
    /**
     * Creates new form Tela_Deposito
     */
    public Tela_Deposito(CadConta cadContaObj) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cadContaObj = cadContaObj;
        this.Label_ConfirmacaoDeposito.setVisible(false);
        this.Label_SaldoFinal.setVisible(false);
        this.Label_NumContaErro.setVisible(false);
        this.Label_ValorDepositoErro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titulo = new javax.swing.JLabel();
        Label_NumConta = new javax.swing.JLabel();
        Input_NumConta = new javax.swing.JTextField();
        Label_NumContaErro = new javax.swing.JLabel();
        Button_ConfirmarDeposito = new javax.swing.JButton();
        Label_ValorDeposito = new javax.swing.JLabel();
        Input_ValorDeposito = new javax.swing.JTextField();
        Label_ValorDepositoErro = new javax.swing.JLabel();
        Label_SaldoFinal = new javax.swing.JLabel();
        Label_ConfirmacaoDeposito = new javax.swing.JLabel();
        Button_RetornarMenuPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Titulo.setBackground(new java.awt.Color(168, 168, 168));
        Label_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Titulo.setText("Depósito em Dinheiro");
        Label_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumConta.setBackground(new java.awt.Color(168, 168, 168));
        Label_NumConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_NumConta.setText("Número da Conta");
        Label_NumConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumContaErro.setForeground(java.awt.Color.red);

        Button_ConfirmarDeposito.setText("Confirmar Depósito");
        Button_ConfirmarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfirmarDepositoActionPerformed(evt);
            }
        });

        Label_ValorDeposito.setBackground(new java.awt.Color(168, 168, 168));
        Label_ValorDeposito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_ValorDeposito.setText("Valor do Depósito");
        Label_ValorDeposito.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_ValorDepositoErro.setForeground(java.awt.Color.red);

        Button_RetornarMenuPrincipal.setText("Retornar ao menu principal");
        Button_RetornarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetornarMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Button_RetornarMenuPrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_NumConta)
                                            .addComponent(Label_ValorDeposito))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Input_NumConta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Input_ValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_ValorDepositoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Label_NumContaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(Label_SaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Button_ConfirmarDeposito)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Label_ConfirmacaoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(Label_Titulo)))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_NumConta)
                        .addComponent(Input_NumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_NumContaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Label_ValorDeposito)
                        .addComponent(Input_ValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_ValorDepositoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_ConfirmacaoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_ConfirmarDeposito))
                .addGap(26, 26, 26)
                .addComponent(Label_SaldoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(Button_RetornarMenuPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ConfirmarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfirmarDepositoActionPerformed
        this.Label_ConfirmacaoDeposito.setText("");
        this.Label_ConfirmacaoDeposito.setVisible(false);
        this.Label_SaldoFinal.setText("");
        this.Label_SaldoFinal.setVisible(false);
        this.Label_NumContaErro.setText("");
        this.Label_NumContaErro.setVisible(false);
        this.Label_ValorDepositoErro.setText("");
        this.Label_ValorDepositoErro.setVisible(false);
        
        int numConta;
        double valorDeposito;
        
        try{
            if (this.Input_NumConta.getText().isEmpty()){
                this.Label_NumContaErro.setText("Insira o número da conta!");
                this.Label_NumContaErro.setVisible(true);
            } 
            if (this.Input_ValorDeposito.getText().isEmpty()){
                this.Label_ValorDepositoErro.setText("Insira o valor do depósito!");
                this.Label_ValorDepositoErro.setVisible(true);
            }
            if ((!this.Input_NumConta.getText().isEmpty()) && (!this.Input_ValorDeposito.getText().isEmpty())){
                numConta = Integer.parseInt(this.Input_NumConta.getText());
                valorDeposito = Double.parseDouble(this.Input_ValorDeposito.getText());
                ArrayList<Conta> listaLocal = cadContaObj.getArrayList();

                boolean encontrou = false;
                int i = 0;
                for (i=0; i<listaLocal.size(); i++){
                    if (listaLocal.get(i).getNumeroConta() == numConta){
                        listaLocal.get(i).Deposito(valorDeposito);
                        cadContaObj.setArrayList(listaLocal);
                        
                        this.Label_ConfirmacaoDeposito.setText("Depósito realizado com sucesso.");
                        this.Label_ConfirmacaoDeposito.setVisible(true);
                        this.Label_SaldoFinal.setText("Saldo da conta: R$" +listaLocal.get(i).getSaldo());
                        this.Label_SaldoFinal.setVisible(true);
                        this.Input_NumConta.setText("");
                        this.Input_ValorDeposito.setText("");
                        encontrou = true;
                    }
                }
                if ((i == listaLocal.size()) && (encontrou == false)){
                    this.Label_NumContaErro.setText("Número da Conta não encontrado.");
                    this.Label_NumContaErro.setVisible(true);
                    this.Input_NumConta.setText("");
                }
            }
        }catch(NumberFormatException e){
            this.Label_NumContaErro.setText("Apenas números são válidos");
            this.Label_NumContaErro.setVisible(true);
            this.Input_NumConta.setText("");
            this.Input_ValorDeposito.setText("");
        }
    }//GEN-LAST:event_Button_ConfirmarDepositoActionPerformed

    private void Button_RetornarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetornarMenuPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Button_RetornarMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ConfirmarDeposito;
    private javax.swing.JButton Button_RetornarMenuPrincipal;
    private javax.swing.JTextField Input_NumConta;
    private javax.swing.JTextField Input_ValorDeposito;
    private javax.swing.JLabel Label_ConfirmacaoDeposito;
    private javax.swing.JLabel Label_NumConta;
    private javax.swing.JLabel Label_NumContaErro;
    private javax.swing.JLabel Label_SaldoFinal;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_ValorDeposito;
    private javax.swing.JLabel Label_ValorDepositoErro;
    // End of variables declaration//GEN-END:variables
    private CadConta cadContaObj;
}