/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Objetos.CadConta;
import Objetos.Conta;
import Objetos.ContaEspecial;
import java.awt.Color;
import java.util.ArrayList;

/**
 *
 * @author Ricardo
 */
public class Tela_RealizarEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form Tela_RealizarEmprestimo
     */
    public Tela_RealizarEmprestimo(CadConta cadContaObj) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cadContaObj = cadContaObj;
        this.Label_NumContaErro.setVisible(false);
        this.Label_ValorEmprestimoErro.setVisible(false);
        this.Label_ConfirmacaoEmprestimo.setVisible(false);
        this.Label_SaldoRestante.setVisible(false);
        this.Label_Erro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Titulo = new javax.swing.JLabel();
        Label_NumConta = new javax.swing.JLabel();
        Input_NumConta = new javax.swing.JTextField();
        Label_NumContaErro = new javax.swing.JLabel();
        Label_ValorEmprestimo = new javax.swing.JLabel();
        Input_ValorEmprestimo = new javax.swing.JTextField();
        Label_ValorEmprestimoErro = new javax.swing.JLabel();
        Button_RealizarEmprestimo = new javax.swing.JButton();
        Button_RetornarMenuPrincipal = new javax.swing.JButton();
        Label_ConfirmacaoEmprestimo = new javax.swing.JLabel();
        Label_SaldoRestante = new javax.swing.JLabel();
        Label_Erro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Label_Titulo.setBackground(new java.awt.Color(168, 168, 168));
        Label_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Titulo.setText("Realizar Empréstimo");
        Label_Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumConta.setBackground(new java.awt.Color(168, 168, 168));
        Label_NumConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_NumConta.setText("Número da Conta");
        Label_NumConta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_NumContaErro.setForeground(java.awt.Color.red);

        Label_ValorEmprestimo.setBackground(new java.awt.Color(168, 168, 168));
        Label_ValorEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Label_ValorEmprestimo.setText("Valor do Empréstimo");
        Label_ValorEmprestimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Label_ValorEmprestimoErro.setForeground(java.awt.Color.red);

        Button_RealizarEmprestimo.setText("Realizar Empréstimo");
        Button_RealizarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RealizarEmprestimoActionPerformed(evt);
            }
        });

        Button_RetornarMenuPrincipal.setText("Voltar ao Menu Principal");
        Button_RetornarMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetornarMenuPrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(Label_Titulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label_ValorEmprestimo)
                                            .addComponent(Label_NumConta))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Input_NumConta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Label_NumContaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Input_ValorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Label_ValorEmprestimoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(Button_RealizarEmprestimo, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_RetornarMenuPrincipal)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Label_Erro, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                        .addComponent(Label_SaldoRestante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Label_ConfirmacaoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_ValorEmprestimo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_NumContaErro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Input_NumConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Label_NumConta)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Input_ValorEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_ValorEmprestimoErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Button_RealizarEmprestimo)
                .addGap(18, 18, 18)
                .addComponent(Label_ConfirmacaoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_SaldoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Erro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Button_RetornarMenuPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_RetornarMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetornarMenuPrincipalActionPerformed
        this.dispose();
    }//GEN-LAST:event_Button_RetornarMenuPrincipalActionPerformed

    private void Button_RealizarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RealizarEmprestimoActionPerformed
        this.Label_ConfirmacaoEmprestimo.setText("");
        this.Label_ConfirmacaoEmprestimo.setVisible(false);
        this.Label_SaldoRestante.setText("");
        this.Label_SaldoRestante.setVisible(false);
        this.Label_Erro.setText("");
        this.Label_Erro.setVisible(false);
        this.Label_NumContaErro.setText("");
        this.Label_NumContaErro.setVisible(false);
        this.Label_ValorEmprestimoErro.setText("");
        this.Label_ValorEmprestimoErro.setVisible(false);
        
        int numConta;
        double valorEmprestimo;
        
        try{
            if (this.Input_NumConta.getText().isEmpty()){
                this.Label_NumContaErro.setText("Insira o número da conta!");
                this.Label_NumContaErro.setVisible(true);
            } 
            if (this.Input_ValorEmprestimo.getText().isEmpty()){
                this.Label_ValorEmprestimoErro.setText("Insira o valor do depósito!");
                this.Label_ValorEmprestimoErro.setVisible(true);
            }
            if ((!this.Input_NumConta.getText().isEmpty()) && (!this.Input_ValorEmprestimo.getText().isEmpty())){
                numConta = Integer.parseInt(this.Input_NumConta.getText());
                valorEmprestimo = Double.parseDouble(this.Input_ValorEmprestimo.getText());
                ArrayList<Conta> listaLocal = cadContaObj.getArrayList();
                
                boolean encontrou = false;
                int i = 0;
                for (i=0; i<listaLocal.size(); i++){
                    if (listaLocal.get(i).getNumeroConta() == numConta){
                        if (listaLocal.get(i).getClass() == ContaEspecial.class){
                            ContaEspecial contaEspecialLocal = (ContaEspecial)listaLocal.get(i);
                            
                            contaEspecialLocal.AtualizaBeneficios();
                            double taxaAtual = contaEspecialLocal.getTaxa();
                            
                            switch(contaEspecialLocal.RealizarEmprestimo(valorEmprestimo)){
                                case 0:
                                    this.Label_ConfirmacaoEmprestimo.setText("Você tem uma dívida pendente! Pague-a primeiro.");
                                    this.Label_ConfirmacaoEmprestimo.setVisible(true);
                                    this.Label_SaldoRestante.setText("Você ainda deve R$" +contaEspecialLocal.getDivida());
                                    this.Label_SaldoRestante.setForeground(Color.red);
                                    this.Label_SaldoRestante.setVisible(true);
                                    this.Input_NumConta.setText("");
                                    this.Input_ValorEmprestimo.setText("");
                                    break;
                                case 1:
                                    this.Label_ConfirmacaoEmprestimo.setText("Empréstimo de R$" +valorEmprestimo+ " realizado a uma taxa de " +taxaAtual+ "%. Você agora deve R$" +contaEspecialLocal.getDivida());
                                    this.Label_ConfirmacaoEmprestimo.setVisible(true);
                                    this.Label_SaldoRestante.setText("Saldo atual da conta: R$" +contaEspecialLocal.getSaldo());
                                    this.Label_SaldoRestante.setVisible(true);
                                    this.Label_Erro.setText("*Para quitar a dívida, basta realizar um depósito: o valor é descontado do saldo.");
                                    this.Label_Erro.setVisible(true);
                                    this.Input_NumConta.setText("");
                                    this.Input_ValorEmprestimo.setText("");
                                    listaLocal.set(i, contaEspecialLocal);
                                    cadContaObj.setArrayList(listaLocal);
                                    break;
                                case 2:
                                    this.Label_ConfirmacaoEmprestimo.setText("Valor do empréstimo maior que o limite da conta!");
                                    this.Label_ConfirmacaoEmprestimo.setForeground(Color.red);
                                    this.Label_ConfirmacaoEmprestimo.setVisible(true);
                                    this.Label_SaldoRestante.setText("Limite da conta: R$" +contaEspecialLocal.getLimite());
                                    this.Label_SaldoRestante.setForeground(Color.red);
                                    this.Label_SaldoRestante.setVisible(true);
                                    this.Input_ValorEmprestimo.setText("");
                                    break;
                                case 3:
                                    this.Label_ConfirmacaoEmprestimo.setText("Você não possui limite suficiente!");
                                    this.Label_ConfirmacaoEmprestimo.setForeground(Color.red);
                                    this.Label_ConfirmacaoEmprestimo.setVisible(true);
                                    this.Label_SaldoRestante.setText("O seu limite atual é: R$" +contaEspecialLocal.getLimite());
                                    this.Label_SaldoRestante.setForeground(Color.red);
                                    this.Label_SaldoRestante.setVisible(true);
                                    this.Input_NumConta.setText("");
                                    this.Input_ValorEmprestimo.setText("");
                                    break;
                                default:
                                    this.Label_Erro.setText("Ocorreu um erro ao realizar o switch()");
                                    this.Label_Erro.setForeground(Color.red);
                                    this.Label_Erro.setVisible(true);
                                    this.Input_NumConta.setText("");
                                    this.Input_ValorEmprestimo.setText("");
                            }
                        }else{
                            this.Label_NumContaErro.setText("Essa não é uma Conta Especial!");
                            this.Label_NumContaErro.setVisible(true);
                            this.Input_NumConta.setText("");
                        }
                        encontrou = true;
                    }
                }
                if ((i == listaLocal.size()) && (encontrou == false)){
                    this.Label_NumContaErro.setText("Essa conta não existe!");
                    this.Label_NumContaErro.setVisible(true);
                    this.Input_NumConta.setText("");
                }
            }
        }catch(NumberFormatException e){
            this.Label_NumContaErro.setText("Apenas números são válidos!");
            this.Label_NumContaErro.setVisible(true);
            this.Input_NumConta.setText("");
            this.Input_ValorEmprestimo.setText("");
        }catch(Error e){
            throw new Error("Erro inesperado ao try{button_SalvarActionPerformed}");
        }
    }//GEN-LAST:event_Button_RealizarEmprestimoActionPerformed

    /**
     * @param args the command line arguments
     */

    private CadConta cadContaObj;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_RealizarEmprestimo;
    private javax.swing.JButton Button_RetornarMenuPrincipal;
    private javax.swing.JTextField Input_NumConta;
    private javax.swing.JTextField Input_ValorEmprestimo;
    private javax.swing.JLabel Label_ConfirmacaoEmprestimo;
    private javax.swing.JLabel Label_Erro;
    private javax.swing.JLabel Label_NumConta;
    private javax.swing.JLabel Label_NumContaErro;
    private javax.swing.JLabel Label_SaldoRestante;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_ValorEmprestimo;
    private javax.swing.JLabel Label_ValorEmprestimoErro;
    // End of variables declaration//GEN-END:variables
}
